/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "load.h"

double *
add_sum_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */

	result = argp->a + argp->b;

	return &result;
}
