/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_return_code (XDR *xdrs, return_code *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_authorization_token_response (XDR *xdrs, authorization_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_return_code (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_request_token, TOKEN_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_request (XDR *xdrs, access_token_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->request_token, TOKEN_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->id, USER_ID_LENGTH))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_response (XDR *xdrs, access_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_return_code (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, TOKEN_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, TOKEN_LEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lifetime))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token_approval_request (XDR *xdrs, token_approval_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->request_token, TOKEN_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token_approval_response (XDR *xdrs, token_approval_response *objp)
{
	register int32_t *buf;

	 if (!xdr_return_code (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->request_token, TOKEN_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action (XDR *xdrs, action *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action_request (XDR *xdrs, action_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_action (xdrs, &objp->act))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->action_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, TOKEN_LEN))
		 return FALSE;
	return TRUE;
}
