apiVersion: v1
kind: Secret
metadata:
  name: nginx-deployment
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitea-http.gitea.svc.cluster.local:3000/adrian.dumitrache02/nginx-deployment.git
  project: default
  name: nginx-deployment
