apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-courses
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/adrian.dumitrache02/nginx-deployment.git
    targetRevision: HEAD
    path: website
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
