build:
	gcc rank_sort.c -o rank_sort -lpthread -lm
	gcc elem_count.c -o elem_count -lpthread -lm
	gcc abstract_tasks.c -o abstract_tasks -lpthread -lm
clean:
	rm -rf rank_sort elem_count abstract_tasks
