<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/style.css" />
    <!-- Include jQuery here to make $(...) useable from inline scripts -->
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>

    <title><?= (!empty($pageTitle) ? $pageTitle . ' - CatzBook' : "CatzBook - Welcome, my fluffy friend!" ) ?></title>

    <?php include("_inc_xssim.phtml"); ?>
  </head>
  <body class="<?=(isset($customBodyClass) ? $customBodyClass : '' )?>">

<?php
$activeLink = function ($controller, $action=null) use ($currentController, $currentAction) {
  if ($controller == $currentController && (empty($action) || $action == $currentAction))
    return ' active';
  return '';
}
?>
<!-- 100% height container -->
<div class="flex-grow-1 d-flex flex-column">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-sm navbar-dark bg-book navbar-nav-scroll fixed-top position-sticky">
    <div class="container">
      <a class="navbar-brand" href="/">CatzBook</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
          data-target="#navbarResponsive" aria-controls="navbarResponsive"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <?php if (empty($authUser)) { ?>
            <li class="nav-item<?= $activeLink("index") ?>">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item<?= $activeLink("auth", "fake_register") ?>">
              <a class="nav-link" href="/auth/fake_register">Register</a>
            </li>
            <?php if ($currentController == "auth" && $currentAction == "register") { ?>
            <li class="nav-item<?= $activeLink("auth", "register") ?>">
              <a class="nav-link" href="/auth/register_real_one">Real Register</a>
            </li>
            <?php } ?>
            <li class="nav-item">
              <a class="nav-link" href="#"
                onclick="alert('Meet you at midnight!')">Contact</a>
            </li>
          <?php } else {?>
            <li class="nav-item<?= $activeLink("inside", "profile") ?>">
              <a class="nav-link" href="/inside/p/<?=$authUser['username']?>">Profile</a>
            </li>
            <li class="nav-item<?= $activeLink("inside/message") ?>">
              <a class="nav-link" href="/inside/message">
                <i class="bi bi-envelope-fill"></i> Messages</a>
            </li>
            <li class="nav-item">
              <a class="nav-link logout" href="/auth/logout">Logout</a>
            </li>
          <?php } ?>
        </ul>
      </div>
    </div>
  </nav>

