<?php include('_header.phtml'); ?>

  <!-- Content section -->
  <section class="py-5 flex-fill" style="margin-top: 4rem;">
    <div class="container">
      <h1 style="color: #900;">We don't do that here!</h1>
      <div class="row align-items-center">
        <div class="col-7">
          <img src="/images/wedontdothat.jpg" alt="We don't do that here!" 
            style="max-width: 100%;" />
        </div>
        <div class="col-5">
          <h2 style="color: #900;">
          <!-- <a href="/auth/register_real_one">Please try again!</a> -->
            You must receive your registration URL from a trusted feline member!
          </h2>
        </div>
      </div>
    </div>
  </section>

</div>

<?php include('_footer.phtml'); ?>
