// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/backend.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_proto_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Reply) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDataRequest) Reset() {
	*x = PostDataRequest{}
	mi := &file_proto_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDataRequest) ProtoMessage() {}

func (x *PostDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDataRequest.ProtoReflect.Descriptor instead.
func (*PostDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{2}
}

func (x *PostDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostDataRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Json          string                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_proto_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDataRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_proto_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeleteDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_proto_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatisticsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetStatisticsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_backend_proto protoreflect.FileDescriptor

const file_proto_backend_proto_rawDesc = "" +
	"\n" +
	"\x13proto/backend.proto\x12\abackend\"3\n" +
	"\x05Reply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"8\n" +
	"\x0eGetDataRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\x0fPostDataRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"O\n" +
	"\x11UpdateDataRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04json\x18\x03 \x01(\tR\x04json\";\n" +
	"\x11DeleteDataRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\x14GetStatisticsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xad\x02\n" +
	"\rbusinessLogic\x122\n" +
	"\aGetData\x12\x17.backend.GetDataRequest\x1a\x0e.backend.Reply\x124\n" +
	"\bPostData\x12\x18.backend.PostDataRequest\x1a\x0e.backend.Reply\x128\n" +
	"\n" +
	"UpdateData\x12\x1a.backend.UpdateDataRequest\x1a\x0e.backend.Reply\x128\n" +
	"\n" +
	"DeleteData\x12\x1a.backend.DeleteDataRequest\x1a\x0e.backend.Reply\x12>\n" +
	"\rGetStatistics\x12\x1d.backend.GetStatisticsRequest\x1a\x0e.backend.ReplyB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_backend_proto_rawDescOnce sync.Once
	file_proto_backend_proto_rawDescData []byte
)

func file_proto_backend_proto_rawDescGZIP() []byte {
	file_proto_backend_proto_rawDescOnce.Do(func() {
		file_proto_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backend_proto_rawDesc), len(file_proto_backend_proto_rawDesc)))
	})
	return file_proto_backend_proto_rawDescData
}

var file_proto_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_backend_proto_goTypes = []any{
	(*Reply)(nil),                // 0: backend.Reply
	(*GetDataRequest)(nil),       // 1: backend.GetDataRequest
	(*PostDataRequest)(nil),      // 2: backend.PostDataRequest
	(*UpdateDataRequest)(nil),    // 3: backend.UpdateDataRequest
	(*DeleteDataRequest)(nil),    // 4: backend.DeleteDataRequest
	(*GetStatisticsRequest)(nil), // 5: backend.GetStatisticsRequest
}
var file_proto_backend_proto_depIdxs = []int32{
	1, // 0: backend.businessLogic.GetData:input_type -> backend.GetDataRequest
	2, // 1: backend.businessLogic.PostData:input_type -> backend.PostDataRequest
	3, // 2: backend.businessLogic.UpdateData:input_type -> backend.UpdateDataRequest
	4, // 3: backend.businessLogic.DeleteData:input_type -> backend.DeleteDataRequest
	5, // 4: backend.businessLogic.GetStatistics:input_type -> backend.GetStatisticsRequest
	0, // 5: backend.businessLogic.GetData:output_type -> backend.Reply
	0, // 6: backend.businessLogic.PostData:output_type -> backend.Reply
	0, // 7: backend.businessLogic.UpdateData:output_type -> backend.Reply
	0, // 8: backend.businessLogic.DeleteData:output_type -> backend.Reply
	0, // 9: backend.businessLogic.GetStatistics:output_type -> backend.Reply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_backend_proto_init() }
func file_proto_backend_proto_init() {
	if File_proto_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backend_proto_rawDesc), len(file_proto_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backend_proto_goTypes,
		DependencyIndexes: file_proto_backend_proto_depIdxs,
		MessageInfos:      file_proto_backend_proto_msgTypes,
	}.Build()
	File_proto_backend_proto = out.File
	file_proto_backend_proto_goTypes = nil
	file_proto_backend_proto_depIdxs = nil
}
